// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8essIZDRDbR2ummWoY9B5iShAMXbcQIE',
    appId: '1:480176577464:web:690a2928e35f1c72b64d4d',
    messagingSenderId: '480176577464',
    projectId: 'todo-app-55d7d',
    authDomain: 'todo-app-55d7d.firebaseapp.com',
    storageBucket: 'todo-app-55d7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgy4LaLe_NmLuV_F9OLpJxMBfVDmDkT5M',
    appId: '1:480176577464:android:21e1e4212212303cb64d4d',
    messagingSenderId: '480176577464',
    projectId: 'todo-app-55d7d',
    storageBucket: 'todo-app-55d7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBy5mQBoH-a0grVWqrkIUaTzj26cUO1l0',
    appId: '1:480176577464:ios:b5630ea58fc550cbb64d4d',
    messagingSenderId: '480176577464',
    projectId: 'todo-app-55d7d',
    storageBucket: 'todo-app-55d7d.appspot.com',
    iosClientId: '480176577464-25mmafadmsgf9p1ad6o6pmeiccgaf25s.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoRefactor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBy5mQBoH-a0grVWqrkIUaTzj26cUO1l0',
    appId: '1:480176577464:ios:bdebc1ec5bc034c1b64d4d',
    messagingSenderId: '480176577464',
    projectId: 'todo-app-55d7d',
    storageBucket: 'todo-app-55d7d.appspot.com',
    iosClientId: '480176577464-i6to96cs5dl733euivh96m9rv31vnsfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoRefactor.RunnerTests',
  );
}
